/* Cloud Run Job entrypoint: Sheets → transform → MK overlay → validate → GitHub PR.
 *
 *   node job.js            # full run: opens a PR if pricing-data.json changed
 *   node job.js --dry-run  # reads + validates + prints the diff, opens nothing
 *
 * Required env: MASTER_SHEET_ID (+ MASTER_SHEET_RANGE). GitHub auth from
 * GITHUB_TOKEN_SECRET (Secret Manager resource name) or GITHUB_TOKEN (local).
 */
import { SecretManagerServiceClient } from '@google-cloud/secret-manager';
import { readSheetObjects } from './lib/sheets.js';
import { transform } from './lib/transform.js';
import { loadMkOverlay, applyMkOverlay } from './lib/mk.js';
import { validate } from './lib/validate.js';
import { makeClient, getCurrentPricing, openPricingPr } from './lib/github.js';

const DRY_RUN = process.argv.includes('--dry-run');

async function getGithubToken() {
  if (process.env.GITHUB_TOKEN) return process.env.GITHUB_TOKEN; // local dev
  const name = process.env.GITHUB_TOKEN_SECRET; // projects/<id>/secrets/<name>/versions/latest
  if (!name) throw new Error('Set GITHUB_TOKEN (local) or GITHUB_TOKEN_SECRET (Secret Manager resource name)');
  const client = new SecretManagerServiceClient();
  const [version] = await client.accessSecretVersion({ name });
  return version.payload.data.toString('utf8').trim();
}

function diffSummary(next, prev) {
  const n = next.repairs.length;
  const p = prev?.repairs?.length ?? 0;
  const withMk = next.repairs.filter((r) => r.mk_price != null).length;
  const delta = p ? ` (was ${p}, ${n - p >= 0 ? '+' : ''}${n - p})` : '';
  return [
    `Automated pricing sync — ${next.generated}`,
    '',
    `- Repairs: ${n}${delta}`,
    `- Mobile Klinik comparisons: ${withMk} / ${n}`,
    `- Source: ${next.source}`,
    '',
    'Generated by the Cloud Run `pricing-sync` job. Review the diff before merging.',
  ].join('\n');
}

async function main() {
  const sheetId = process.env.MASTER_SHEET_ID;
  const range = process.env.MASTER_SHEET_RANGE || 'Master!A1:Z10000';
  if (!sheetId) throw new Error('MASTER_SHEET_ID is required');

  const rows = await readSheetObjects(sheetId, range);

  const data = transform(rows);
  applyMkOverlay(data, await loadMkOverlay());
  const mkCount = data.repairs.filter((r) => r.mk_price != null).length;

  // GitHub: needed to diff against the live file and to open the PR.
  const haveCreds = !!(process.env.GITHUB_TOKEN || process.env.GITHUB_TOKEN_SECRET);
  const octokit = (!DRY_RUN || haveCreds) ? makeClient(await getGithubToken()) : null;
  const current = octokit ? await getCurrentPricing(octokit) : { json: null, sha: null, raw: null };

  validate(data, current.json);

  const nextContent = JSON.stringify(data, null, 2) + '\n';
  if (current.raw && current.raw.trim() === nextContent.trim()) {
    return;
  }

  if (DRY_RUN) {
    console.log(diffSummary(data, current.json));
    return;
  }

  const url = await openPricingPr(octokit, {
    newContent: nextContent,
    currentSha: current.sha,
    summary: diffSummary(data, current.json),
    date: data.generated,
  });
}

main().catch((err) => { console.error('[sync] FAILED:', err?.message || err); process.exit(1); });
