/* Cloud Run Job entrypoint: Google Places reviews → validate → GitHub PR.
 *
 *   node job.js            # full run: opens a PR if reviews.json changed
 *   node job.js --dry-run  # fetches + validates + prints the diff, opens nothing
 *
 * Required env: GOOGLE_PLACE_ID. Places key from GOOGLE_PLACES_API_KEY (local) or
 * GOOGLE_PLACES_API_KEY_SECRET (Secret Manager resource name). GitHub auth from
 * GITHUB_TOKEN (local) or GITHUB_TOKEN_SECRET. Optional: REVIEWS_MIN_RATING (default 0),
 * REVIEWS_MAX (default 6).
 */
import { SecretManagerServiceClient } from '@google-cloud/secret-manager';
import { fetchReviews } from './lib/places.js';
import { validate } from './lib/validate.js';
import { makeClient, getCurrentReviews, openReviewsPr } from './lib/github.js';

const DRY_RUN = process.argv.includes('--dry-run');

async function readSecret(name) {
  const client = new SecretManagerServiceClient();
  const [version] = await client.accessSecretVersion({ name });
  return version.payload.data.toString('utf8').trim();
}

async function getPlacesKey() {
  if (process.env.GOOGLE_PLACES_API_KEY) return process.env.GOOGLE_PLACES_API_KEY; // local dev
  const name = process.env.GOOGLE_PLACES_API_KEY_SECRET; // projects/<id>/secrets/<name>/versions/latest
  if (!name) throw new Error('Set GOOGLE_PLACES_API_KEY (local) or GOOGLE_PLACES_API_KEY_SECRET (Secret Manager resource name)');
  return readSecret(name);
}

async function getGithubToken() {
  if (process.env.GITHUB_TOKEN) return process.env.GITHUB_TOKEN; // local dev
  const name = process.env.GITHUB_TOKEN_SECRET;
  if (!name) throw new Error('Set GITHUB_TOKEN (local) or GITHUB_TOKEN_SECRET (Secret Manager resource name)');
  return readSecret(name);
}

function diffSummary(next, prev) {
  const n = next.reviews.length;
  const p = prev?.reviews?.length ?? 0;
  return [
    `Automated reviews sync — ${next.generated}`,
    '',
    `- Rating: ${next.rating ?? '—'} (${next.review_count} total)`,
    `- Reviews shown: ${n}${p ? ` (was ${p})` : ''}`,
    `- Source: ${next.source}`,
    '',
    'Generated by the Cloud Run `reviews-sync` job. Review the diff before merging.',
  ].join('\n');
}

async function main() {
  const placeId = process.env.GOOGLE_PLACE_ID;
  if (!placeId) throw new Error('GOOGLE_PLACE_ID is required');
  const minRating = Number(process.env.REVIEWS_MIN_RATING || 0);
  const max = Number(process.env.REVIEWS_MAX || 6);

  console.log(`[reviews] fetching Places details for ${placeId}`);
  const data = await fetchReviews(placeId, await getPlacesKey(), { minRating, max });
  console.log(`[reviews] rating ${data.rating}, ${data.review_count} total, ${data.reviews.length} shown`);

  // GitHub: needed to diff against the live file and to open the PR.
  const haveCreds = !!(process.env.GITHUB_TOKEN || process.env.GITHUB_TOKEN_SECRET);
  const octokit = (!DRY_RUN || haveCreds) ? makeClient(await getGithubToken()) : null;
  const current = octokit ? await getCurrentReviews(octokit) : { json: null, sha: null, raw: null };

  validate(data, current.json);
  console.log('[reviews] validation passed');

  const nextContent = JSON.stringify(data, null, 2) + '\n';
  if (current.raw && current.raw.trim() === nextContent.trim()) {
    console.log('[reviews] no changes — reviews.json already current.');
    return;
  }

  if (DRY_RUN) {
    console.log('[reviews] DRY RUN — no PR opened.\n');
    console.log(diffSummary(data, current.json));
    return;
  }

  const url = await openReviewsPr(octokit, {
    newContent: nextContent,
    currentSha: current.sha,
    summary: diffSummary(data, current.json),
    date: data.generated,
  });
  console.log(`[reviews] opened PR: ${url}`);
}

main().catch((err) => { console.error('[reviews] FAILED:', err?.message || err); process.exit(1); });
